### ISSUE TITLE
"Cannot read property 'ids' of undefined" when trying to build for android

### ISSUE THREAD

**Issue by greyarch** [expo/exp#23]
I get this error when trying to do "exp build:android" on MacOS. Here is the full stack trace:

exp build:android
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Starting build process...
[exp] Cannot read property 'ids' of undefined
TypeError: Cannot read property 'ids' of undefined
    at AndroidBuilder._callee4$ (/usr/local/lib/node_modules/exp/build/commands/build/BaseBuilder.js:270:31)
    at tryCatch (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/usr/local/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13

**Comment by dikaiosune** [comment]
Hi @greyarch -- thanks for the report. What's the output of running `exp --version` on your machine?

**Comment by greyarch** [comment]
Hey @dikaiosune, this is what I get:
```
exp --version
0.30.0
```
I only installed exp today

**Comment by greyarch** [comment]
I found what the problem was - apparently I've missed a config step and did not put the android package section in the exp.json file. Once I put something like
```
...
"android": {
     "package": "my.paackage.id"
}
...
```
in the **exp.json** file the build started correctly.

**Comment by dikaiosune** [comment]
@greyarch thanks for posting back! I'm so sorry I wasn't able to follow up on this earlier. We definitely need to improve this error message, so I'm going to reopen this issue as a reminder to work on this.

**Comment by brentvatne** [comment]
moved to https://github.com/expo/expo/issues/171
