### ISSUE TITLE
Non interactive login not working

### ISSUE THREAD

**Issue by atinder** [expo/exp#61]
exp login -u myUsername -p myPassword

throws

```
[exp] invalid_request
Error: invalid_request
    at _formatAuth0NodeError (/xdl/src/User.js:785:39)
    at /xdl/src/User.js:682:21
    at Generator.throw (<anonymous>)
    at step (/home/ubuntu/.nvm/versions/node/v7.10.0/lib/node_modules/exp/node_modules/xdl/build/User.js:188:191)
    at /home/ubuntu/.nvm/versions/node/v7.10.0/lib/node_modules/exp/node_modules/xdl/build/User.js:188:402

```
Interactive login works with the same username and password.

**Comment by dikaiosune** [comment]
Hi! As requested in the issue template, please open issues on the central Expo repository: https://github.com/expo/expo. Thanks!
